import operations
from operations import driver, reset, give_input, set_up

if __name__ == "__main__":
    reset()
    set_up()
    give_input(2)
    reset()
    give_input(5)
    give_input(21)
    reset()
    give_input(4)
    give_input(18)
    give_input(9)
    reset()
    give_input(12)
    reset()
    give_input(3)
    give_input(17)
    #reset() #TODO it doesn't close if reset is last?

    driver.quit()


#THIS FILE SHOULD BE AUTOMATICALLY GENERATED BY MY OTHER PROGRAM, THIS IS JUST A PLACEHOLDER