#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Ubuntu
# See docs for Running Windows and Linux builds side-by-side

# scripts that are called at very beginning, before repo cloning
# init:
#   - git config --global core.autocrlf input

#---------------------------------#
#       build configuration       #
#---------------------------------#

build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
- sh: >-
    ./eltelive.sh
    ./eltelive.sh
    ls deploy/log
    whoami

# #---------------------------------#
# #      artifacts configuration    #
# #---------------------------------#

artifacts:

# pushing entire folder as a zip archive
  - path: deploy/log