#!/bin/sh

# There are two typical installation scenarios.
# If you want to run in a container, choose docker and alpine below!
# If you want to directly install on your system, choose host and debian!

# Containerization to use
#   docker - Use Docker container to run the installation
#   host     - Install directly on host (your) system (run as root in this case)
EL_CONTAINER="docker"

# Linux distribution family to install on
#   alpine  - Alpine Linux for making small containers
#   debian - Any Debian-based system, including Ubuntu and derivatives
EL_OS="alpine"

# Container name in case of using Docker
EL_CONTAINERNAME="eltelive"

# Restart service automatically if it dies?
EL_AUTORESTART="no"
